<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>381a0860-7a9d-4510-83fd-08452c3f99cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Select' or . = 'Select') and @ref_element = 'Object Repository/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_ea9ac7']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ProductCatalogMainBody']/div/div/div/div[2]/div/div/div/div[7]/div[2]/div/div/div/div[5]/div/div/div[2]/div[2]/a[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9b93b96-7344-48ea-94bf-47ed86ac60fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-caption</value>
      <webElementGuid>54fd9325-0191-4b5c-975c-80a604b041ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>evaluateText: 'Select', evaluateAttr: { title: '' }</value>
      <webElementGuid>cc6824e9-5e6e-4658-af27-43e406f22d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>922984a2-940e-4043-b24e-d8da011c2f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductCatalogMainBody&quot;)/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-vertical&quot;]/div[@class=&quot;form-container evaluate-form-container FormContainerStretchFlex&quot;]/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-vertical&quot;]/div[@class=&quot;container-element layout-flow-horizontal ProductCatalogCategoriesFilterAndProductContainer&quot;]/div[@class=&quot;container-element layout-flow-horizontal ProductCatalogProductContainer&quot;]/div[@class=&quot;container-element layout-flow-vertical ProductListContainer&quot;]/div[@class=&quot;list SearchCardListProductCatalog&quot;]/div[@class=&quot;list-items-container&quot;]/div[@class=&quot;list-item&quot;]/div[@class=&quot;container-element layout-flow-vertical ProductCatalogCard&quot;]/div[@class=&quot;container-element layout-flow-vertical ProductCatalogBody&quot;]/div[@class=&quot;container-element layout-flow-horizontal ProductCatalogFieldGroup&quot;]/div[@class=&quot;container-element layout-flow-vertical&quot;]/a[@class=&quot;button button-element with-text&quot;]/span[@class=&quot;v-caption&quot;]</value>
      <webElementGuid>28d138f3-79da-4ce2-b6a5-cd376e1112a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_edb359</value>
      <webElementGuid>bd6fe9c4-2c4d-4030-a0f2-864a8a0bd4cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProductCatalogMainBody']/div/div/div/div[2]/div/div/div/div[7]/div[2]/div/div/div/div[5]/div/div/div[2]/div[2]/a[6]/span</value>
      <webElementGuid>61060aab-9d78-426b-9aed-56ac7c9b45c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[10]/following::span[1]</value>
      <webElementGuid>cb63f504-517b-4ff4-93a7-f699894c0742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[9]/following::span[2]</value>
      <webElementGuid>87822148-668b-41eb-a210-112529ebc9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Item'])[28]/preceding::span[1]</value>
      <webElementGuid>b658e7d7-eb10-455b-91df-9df9b1841edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Item'])[29]/preceding::span[2]</value>
      <webElementGuid>9d0f789d-06d8-4365-8928-41a9402b77e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div[2]/a[6]/span</value>
      <webElementGuid>19a48600-0369-4cb8-854d-8143d5051808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>afd71c26-597a-48a0-8a28-6c70dcf48cf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
