<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Customer</name>
   <tag></tag>
   <elementGuidId>81daf670-c1cb-48f6-bea8-d78b2a1857ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DirectQuoteBody']/div/div/div/div/div/div/div/div/div[3]/a[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a5e73d6-6951-4f16-8ff4-91e765887af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-caption</value>
      <webElementGuid>b77dcf0a-4d56-4843-8081-62e5bd4c807d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>evaluateText: 'Select Customer', evaluateAttr: { title: '' }</value>
      <webElementGuid>62efe500-e57a-4992-adaf-50f92dc732c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Customer</value>
      <webElementGuid>0b907ba0-11a4-4216-a6f8-001be0f0cda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectQuoteBody&quot;)/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-horizontal ContainerStretch&quot;]/div[@class=&quot;container-element layout-flow-vertical QuoteBodyMainArea&quot;]/div[@class=&quot;form-container evaluate-form-container QuoteCustomerHeader&quot;]/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-horizontal MobileQuoteCustomerHeader&quot;]/div[@class=&quot;container-element layout-flow-vertical QuoteCustomerHeaderChange&quot;]/a[@class=&quot;button button-element with-text with-icon Edit MobileSelectCustomerButtonTertiaryDark&quot;]/span[@class=&quot;v-caption&quot;]</value>
      <webElementGuid>2e63c589-eea7-4494-8268-167f6e772d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KINRO_TST/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_ea9ac7</value>
      <webElementGuid>5810417b-b717-4604-ad39-f89dd2b17605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirectQuoteBody']/div/div/div/div/div/div/div/div/div[3]/a[3]/span</value>
      <webElementGuid>bb0c7e27-4558-4b83-9fcc-3f913e660ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Customer'])[1]/following::span[1]</value>
      <webElementGuid>11360e07-f1e9-4582-9430-64098d3b29a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Customer'])[1]/following::span[2]</value>
      <webElementGuid>6ad7399e-363e-4e22-baeb-d6aa35d65048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last modified by Seth Romanowski on 3/12/2024 6:58 PM'])[1]/preceding::span[1]</value>
      <webElementGuid>6c18257e-461b-45d5-88ac-bd4c61a51475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lines: 0'])[1]/preceding::span[2]</value>
      <webElementGuid>10ad2287-d2e8-4cf4-9de7-d3b28cd7f1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Customer']/parent::*</value>
      <webElementGuid>acd0d884-7118-4c71-8fd7-5def07dd772f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>9b2e8217-3731-4a08-af81-01ef251a9fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Customer' or . = 'Select Customer')]</value>
      <webElementGuid>3a477440-96f7-471b-a581-1f26d6e64ff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
