<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DQ002574-1</name>
   <tag></tag>
   <elementGuidId>179317bd-75d3-44b7-8242-6b6e9c5dcd7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DirectQuoteListContainer']/div/div/div/div[2]/div[2]/div/div/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.link.SearchCardTitle > span.v-caption</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee2cd17b-9e47-4a31-aa7b-b4ad73288920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-caption</value>
      <webElementGuid>c2235b09-5b63-42a4-9b2f-d7da66aba0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>evaluateText: '{{record.DirectQuoteNumberString}}', evaluateAttr: { title: '{{record.DirectQuoteNumberString}}' }</value>
      <webElementGuid>90902ed3-6879-4378-afbf-d24ec08b33bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DQ002574-1</value>
      <webElementGuid>2617d645-8b8d-417a-ad32-4c43f30fe9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DQ002574-1</value>
      <webElementGuid>b0fa03f5-79a3-42c9-9235-36b3ae22e60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectQuoteListContainer&quot;)/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-vertical Width100Percent&quot;]/div[@class=&quot;container-element layout-flow-vertical QuoteOrderFormBody&quot;]/div[@class=&quot;list SearchCardList&quot;]/div[@class=&quot;list-items-container&quot;]/div[@class=&quot;list-item&quot;]/div[@class=&quot;container-element layout-flow-vertical SearchCard&quot;]/div[@class=&quot;container-element layout-flow-horizontal SearchCardHeader&quot;]/a[@class=&quot;link SearchCardTitle&quot;]/span[@class=&quot;v-caption&quot;]</value>
      <webElementGuid>3eb51ac6-4b43-42e4-bfa7-f864f1c2ddd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Enjoy easier navigation and personal_ea9ac7</value>
      <webElementGuid>727bcd21-e8f3-42ac-8aa0-d6b318c91bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirectQuoteListContainer']/div/div/div/div[2]/div[2]/div/div/div/div/a/span</value>
      <webElementGuid>4420b28d-f712-46a3-94e7-5d3f7c61414d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/following::span[1]</value>
      <webElementGuid>f0c25cd0-1d7f-4e3b-ad9f-4c7f6e1dc201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/following::span[2]</value>
      <webElementGuid>31efa059-b37a-47d8-a6d8-aa114b3d21be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::span[2]</value>
      <webElementGuid>a909766c-67d1-4b8f-909c-e86f48e33ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[3]/preceding::span[3]</value>
      <webElementGuid>0632598a-8beb-4e46-a6c3-3eee6d3c5597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DQ002574-1']/parent::*</value>
      <webElementGuid>0bc50433-77bd-4fee-bd00-a20cfcc4199a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/span</value>
      <webElementGuid>a36480d5-acbf-45fa-89e5-07151b660a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'DQ002574-1' and (text() = 'DQ002574-1' or . = 'DQ002574-1')]</value>
      <webElementGuid>b720d62b-fe36-47bb-8c24-3fa3a547c361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
