<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Customer</name>
   <tag></tag>
   <elementGuidId>dd4fe008-59c1-44b3-84bf-a3b4d8b54e8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DirectQuoteBody']/div/div/div/div/div/div/div/div/div[3]/a[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5e9c46d2-3e9b-4c8e-9b7d-80355dc39145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-caption</value>
      <webElementGuid>e7378693-3839-4e9b-b4ce-97790c3716f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>evaluateText: 'Select Customer', evaluateAttr: { title: '' }</value>
      <webElementGuid>b3f4816d-6b19-417e-b069-f4bedcfa7166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Customer</value>
      <webElementGuid>7f7901e8-adaa-41a0-8678-4f48acda8991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectQuoteBody&quot;)/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-horizontal ContainerStretch&quot;]/div[@class=&quot;container-element layout-flow-vertical QuoteBodyMainArea&quot;]/div[@class=&quot;form-container evaluate-form-container QuoteCustomerHeader&quot;]/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-horizontal MobileQuoteCustomerHeader&quot;]/div[@class=&quot;container-element layout-flow-vertical QuoteCustomerHeaderChange&quot;]/a[@class=&quot;button button-element with-text with-icon Edit MobileSelectCustomerButtonTertiaryDark&quot;]/span[@class=&quot;v-caption&quot;]</value>
      <webElementGuid>f72e75fc-9393-46a7-abf1-44dc69e745d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Test/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_ea9ac7</value>
      <webElementGuid>14626fe0-5b3c-404f-98b1-dd22584ce812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirectQuoteBody']/div/div/div/div/div/div/div/div/div[3]/a[3]/span</value>
      <webElementGuid>8abccc0e-3909-44c0-8886-0a30767ad87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Customer'])[1]/following::span[1]</value>
      <webElementGuid>6944bd90-f651-4800-8784-58bcb9cba3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Customer'])[1]/following::span[2]</value>
      <webElementGuid>640eaf49-edf1-46e7-ad6f-e6f1c44753a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last modified by Seth Romanowski on 2/16/2024 8:41 PM'])[1]/preceding::span[1]</value>
      <webElementGuid>7161722b-cc65-48cf-84b8-0ee615497e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lines: 0'])[1]/preceding::span[2]</value>
      <webElementGuid>d25ed87e-34e7-44a9-bdb2-c5ec1610bb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Customer']/parent::*</value>
      <webElementGuid>695ab6de-677b-4f6d-8c41-335b2b0e1e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>dd41818b-1451-4ba7-8ac3-7a2e265020fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Customer' or . = 'Select Customer')]</value>
      <webElementGuid>138f03db-5f75-460d-a9d7-68acb5634564</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
