<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Enjoy easier navigation and personal_edb359</name>
   <tag></tag>
   <elementGuidId>2d0d908a-6a06-4a1b-b7f3-a03725b24f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;cpqeq_e0f89810-ae94-497b-abb7-ec59c88095b9&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='cpqeq_e0f89810-ae94-497b-abb7-ec59c88095b9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>17b18829-a32b-4f6a-a26e-e2ba7e72a021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-app-frame</value>
      <webElementGuid>b6214f5b-8c2d-433c-ab20-23abc9943357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cpqeq_e0f89810-ae94-497b-abb7-ec59c88095b9</value>
      <webElementGuid>7ad19ba2-c5d5-46c0-96a9-d56f477491f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cpqks.inforcloudsuite.com:443/web/enterprisequoting/?DeliveryType=InforGo%2cWeb&amp;HybridCertified=1&amp;portalV2Certified=1&amp;LogicalId=lid%3A%2F%2Finfor.cpqeq.cpqeq&amp;inforThemeName=Light&amp;inforCurrentLocale=en-US&amp;inforCurrentLanguage=en-US&amp;infor10WorkspaceShell=1&amp;inforWorkspaceVersion=2024.02.00&amp;inforStyle=3.0&amp;inforTimeZone=(UTC-05%3A00)%20Eastern%20Time%20(US%20%26%20Canada)&amp;inforStdTimeZone=America%2FNew_York</value>
      <webElementGuid>6deee176-2bec-4d52-afec-866f035ac27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>onAppFrameError(e);</value>
      <webElementGuid>324dc718-2c16-4f70-b30d-dfd0a451285e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation; microphone; camera;</value>
      <webElementGuid>8530793a-a0d2-4b87-8cc0-0cd81f0f4f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appPageKey0&quot;)/iframe[@class=&quot;m-app-frame&quot;]</value>
      <webElementGuid>38d5ae04-b93a-43b0-b355-baf9bf56f06c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='cpqeq_e0f89810-ae94-497b-abb7-ec59c88095b9']</value>
      <webElementGuid>9fdd7d6d-a122-4a70-99e4-69d882c158e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appPageKey0']/iframe</value>
      <webElementGuid>d663e218-3dd0-4a26-9b92-4517ad5527dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>da8856eb-d74d-4c39-9efe-c0f07fdabbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'cpqeq_e0f89810-ae94-497b-abb7-ec59c88095b9' and @src = 'https://cpqks.inforcloudsuite.com:443/web/enterprisequoting/?DeliveryType=InforGo%2cWeb&amp;HybridCertified=1&amp;portalV2Certified=1&amp;LogicalId=lid%3A%2F%2Finfor.cpqeq.cpqeq&amp;inforThemeName=Light&amp;inforCurrentLocale=en-US&amp;inforCurrentLanguage=en-US&amp;infor10WorkspaceShell=1&amp;inforWorkspaceVersion=2024.02.00&amp;inforStyle=3.0&amp;inforTimeZone=(UTC-05%3A00)%20Eastern%20Time%20(US%20%26%20Canada)&amp;inforStdTimeZone=America%2FNew_York']</value>
      <webElementGuid>f7f29da1-ad30-4466-8238-ac8b3fe3e17e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
