<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Enjoy easier navigation and personal_ea9ac7</name>
   <tag></tag>
   <elementGuidId>2d0d908a-6a06-4a1b-b7f3-a03725b24f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fa52428f-092c-4784-ac6b-232c50f215da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-app-frame</value>
      <webElementGuid>256c64f5-f4b3-46c6-a8e2-678b5dfe3114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3</value>
      <webElementGuid>ae51801a-8cf0-46fe-90ea-2948f7bb9f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cpqks.inforcloudsuite.com:443/web/enterprisequoting/?DeliveryType=InforGo%2cWeb&amp;HybridCertified=1&amp;portalV2Certified=1&amp;LogicalId=lid%3A%2F%2Finfor.cpqeq.cpqeq&amp;inforThemeName=Light&amp;inforCurrentLocale=en-US&amp;inforCurrentLanguage=en-US&amp;infor10WorkspaceShell=1&amp;inforWorkspaceVersion=2024.02.00&amp;inforStyle=3.0&amp;inforTimeZone=(UTC-05%3A00)%20Eastern%20Time%20(US%20%26%20Canada)&amp;inforStdTimeZone=America%2FNew_York</value>
      <webElementGuid>4ecc2c6c-20b7-4dac-97d4-dd55f100045e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>onAppFrameError(e);</value>
      <webElementGuid>57cc872f-9ef3-41a5-9bb5-6a72267759d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation; microphone; camera;</value>
      <webElementGuid>62c16756-da88-487d-8483-bfbe2be06df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appPageKey0&quot;)/iframe[@class=&quot;m-app-frame&quot;]</value>
      <webElementGuid>0807146e-628d-403c-ba08-b9032aaccfb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3']</value>
      <webElementGuid>76880c19-f8e4-44f6-9f5a-b4505dbbe9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appPageKey0']/iframe</value>
      <webElementGuid>4540e725-b32a-4028-ad07-86d8799df4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9bda1a83-3cd4-40ff-8464-48ed846b66b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3' and @src = 'https://cpqks.inforcloudsuite.com:443/web/enterprisequoting/?DeliveryType=InforGo%2cWeb&amp;HybridCertified=1&amp;portalV2Certified=1&amp;LogicalId=lid%3A%2F%2Finfor.cpqeq.cpqeq&amp;inforThemeName=Light&amp;inforCurrentLocale=en-US&amp;inforCurrentLanguage=en-US&amp;infor10WorkspaceShell=1&amp;inforWorkspaceVersion=2024.02.00&amp;inforStyle=3.0&amp;inforTimeZone=(UTC-05%3A00)%20Eastern%20Time%20(US%20%26%20Canada)&amp;inforStdTimeZone=America%2FNew_York']</value>
      <webElementGuid>d7017d7f-07a2-425d-939d-cc978826e407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
