<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Enjoy easier navigation and personal_ea9ac7</name>
   <tag></tag>
   <elementGuidId>2d0d908a-6a06-4a1b-b7f3-a03725b24f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f7d2bf5c-44e9-4d62-a1cb-f71addac60db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-app-frame</value>
      <webElementGuid>446d74af-7b27-42bc-9e5f-e92be8960ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3</value>
      <webElementGuid>6245e1f2-ca4c-4e0c-9468-e55a3eec3f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cpqks.inforcloudsuite.com:443/web/enterprisequoting/?DeliveryType=InforGo%2cWeb&amp;HybridCertified=1&amp;portalV2Certified=1&amp;LogicalId=lid%3A%2F%2Finfor.cpqeq.cpqeq&amp;inforThemeName=Light&amp;inforCurrentLocale=en-US&amp;inforCurrentLanguage=en-US&amp;infor10WorkspaceShell=1&amp;inforWorkspaceVersion=2024.02.00&amp;inforStyle=3.0&amp;inforTimeZone=(UTC-05%3A00)%20Eastern%20Time%20(US%20%26%20Canada)&amp;inforStdTimeZone=America%2FNew_York</value>
      <webElementGuid>e8b95a9c-b22d-4110-b19b-5d224c896eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>onAppFrameError(e);</value>
      <webElementGuid>74f5593c-e698-4af2-85ca-ece65da2298d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation; microphone; camera;</value>
      <webElementGuid>ab5af582-8b9c-4694-b3ae-89ac678749de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appPageKey0&quot;)/iframe[@class=&quot;m-app-frame&quot;]</value>
      <webElementGuid>be55fd22-2fe4-4c3b-bce0-922f037c8d01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3']</value>
      <webElementGuid>eca880a0-c9f1-4b23-bd6c-69aee472e815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appPageKey0']/iframe</value>
      <webElementGuid>8ef87155-2545-4039-8eb0-4dc5bc95d8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6d508f13-8dbe-49e4-8f8d-20fb62a941d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'cpqeq_29ab1a72-9fa8-40a4-b29f-f404b2a5e0c3' and @src = 'https://cpqks.inforcloudsuite.com:443/web/enterprisequoting/?DeliveryType=InforGo%2cWeb&amp;HybridCertified=1&amp;portalV2Certified=1&amp;LogicalId=lid%3A%2F%2Finfor.cpqeq.cpqeq&amp;inforThemeName=Light&amp;inforCurrentLocale=en-US&amp;inforCurrentLanguage=en-US&amp;infor10WorkspaceShell=1&amp;inforWorkspaceVersion=2024.02.00&amp;inforStyle=3.0&amp;inforTimeZone=(UTC-05%3A00)%20Eastern%20Time%20(US%20%26%20Canada)&amp;inforStdTimeZone=America%2FNew_York']</value>
      <webElementGuid>31cb4d28-864b-406f-8806-abf239facf09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
