<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Quote App (ONLY)_iframePopup</name>
   <tag></tag>
   <elementGuidId>7704dc41-3ef0-4312-92c4-c56d190d5079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;iframePopup&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='iframePopup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8fcc2c36-7f97-4827-a08c-1229af415ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframePopup</value>
      <webElementGuid>ca94b7ce-67b9-47f8-934d-f51b40df1651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://configuretest.lci1.com/PCM/Configurator/Config.aspx?InstanceID=PCM&amp;AppID=QuotingApp3&amp;HeaderID=7e894e2c-ff76-4b2a-828b-b11a00095c0b&amp;ConfigurationID=7b4e32c3-9504-48e2-9a60-dad3927032ea&amp;PageTitle=&amp;RedirectUrl=https%3A%2F%2Fcpqks.inforcloudsuite.com%2Fweb%2Fenterprisequoting%2FProductConfiguration%2FFinish%3FtargetDomain%3Dhttps%3A%2F%2Fcpqks.inforcloudsuite.com%2Fweb%2Fenterprisequoting%2F</value>
      <webElementGuid>f7fc26fc-4a54-4664-befa-4eb044915129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-popup</value>
      <webElementGuid>b58983eb-7db4-4651-90c1-543abb1c6255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-content&quot;)/iframe[@class=&quot;iframe-popup&quot;]</value>
      <webElementGuid>c3420590-e24c-4c5f-9d10-e548df6137e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_edb359</value>
      <webElementGuid>fc577bda-a9fe-464b-b78c-57f139717835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='iframePopup']</value>
      <webElementGuid>71601434-b7d2-4c45-b829-500d94a38ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-content']/iframe[2]</value>
      <webElementGuid>51d97134-da35-4ecf-9b46-f44fa4bd4fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>bdc34139-3d5a-49fc-a539-b758922780cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'iframePopup' and @src = 'https://configuretest.lci1.com/PCM/Configurator/Config.aspx?InstanceID=PCM&amp;AppID=QuotingApp3&amp;HeaderID=7e894e2c-ff76-4b2a-828b-b11a00095c0b&amp;ConfigurationID=7b4e32c3-9504-48e2-9a60-dad3927032ea&amp;PageTitle=&amp;RedirectUrl=https%3A%2F%2Fcpqks.inforcloudsuite.com%2Fweb%2Fenterprisequoting%2FProductConfiguration%2FFinish%3FtargetDomain%3Dhttps%3A%2F%2Fcpqks.inforcloudsuite.com%2Fweb%2Fenterprisequoting%2F']</value>
      <webElementGuid>d57fbeef-7881-4efe-b666-39c9084edb1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
