<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exact Width_p0s6o0OWIDTHctl00</name>
   <tag></tag>
   <elementGuidId>d6be9aab-1832-468a-9889-980cc5764243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='p0$s6$o0$OWIDTH$ctl00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;p0$s6$o0$OWIDTH$ctl00&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5eb92ab-199a-4f05-8cca-51e6037da035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p0$s6$o0$OWIDTH$ctl00</value>
      <webElementGuid>a2790c58-8b20-454a-b107-ba626975fb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1cf85621-1bd0-4044-9c6e-ab8fad0f85c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8b6de81e-3c2d-4dea-8db8-954af6e7901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ad12f720-828a-4171-96e5-1096b30de9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>autoControlFocused(event);</value>
      <webElementGuid>f911e389-c92a-4cd6-8e52-973259c083e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p0_s6_o0_OWIDTH&quot;)/input[@class=&quot;textbox&quot;]</value>
      <webElementGuid>8452f5a2-243f-4e2e-bb15-deaba40b00e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enterprise Quoting/iframe_Quote App (ONLY)_iframePopup</value>
      <webElementGuid>dfd883ce-833a-4422-ab5f-0312d57afd5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='p0$s6$o0$OWIDTH$ctl00']</value>
      <webElementGuid>2e2a586c-1816-41f5-87a5-3bada202d4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='p0_s6_o0_OWIDTH']/input</value>
      <webElementGuid>5669a292-355c-4f47-b248-e090d280f7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>022326bb-652d-4f78-b1cf-d20b5801dc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'p0$s6$o0$OWIDTH$ctl00' and @type = 'text']</value>
      <webElementGuid>78010c33-c2a1-4b5a-92be-92f61d9d450d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
