<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exact Height_p0s7o0OHEIGHTctl00</name>
   <tag></tag>
   <elementGuidId>55ec99ac-a247-4591-b2ef-3e15de590467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='p0$s7$o0$OHEIGHT$ctl00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;p0$s7$o0$OHEIGHT$ctl00&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdc9ce35-ea3b-4014-8ba5-86993220e93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p0$s7$o0$OHEIGHT$ctl00</value>
      <webElementGuid>77061b18-37b6-49cb-b6ec-3b49036c5562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85d51a7c-2e8e-40f6-8bc8-8bd32c2f493a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>aa6d70a7-0d80-4b03-82ae-689dc3c04f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>20487313-b268-4b91-ae03-e3004848d868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>autoControlFocused(event);</value>
      <webElementGuid>3d8e58f1-2b6b-4eb0-96dc-11c260c51802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p0_s7_o0_OHEIGHT&quot;)/input[@class=&quot;textbox&quot;]</value>
      <webElementGuid>e39fc712-4912-449c-83f0-d3c1de22d7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enterprise Quoting/iframe_Quote App (ONLY)_iframePopup</value>
      <webElementGuid>32a2c801-7314-46cd-ace1-21d9ddfb2d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='p0$s7$o0$OHEIGHT$ctl00']</value>
      <webElementGuid>30a565be-5d7c-4588-9b8c-a911d87d1633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='p0_s7_o0_OHEIGHT']/input</value>
      <webElementGuid>1ce13e29-5b03-4bcf-92f2-b16571499e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/div[2]/span/input</value>
      <webElementGuid>595199f1-8d48-499b-a770-fb2f7727dcdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'p0$s7$o0$OHEIGHT$ctl00' and @type = 'text']</value>
      <webElementGuid>1cb8262b-7225-451f-86c0-797f335017c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
