<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DQ002574-1</name>
   <tag></tag>
   <elementGuidId>a4992149-8ef5-4e85-ac7f-20dd48c4cac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link.SearchCardTitle > span.v-caption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DirectQuoteListContainer']/div/div/div/div[2]/div[2]/div/div/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61466ba9-5bc9-4bcc-8a52-a57be77f1907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-caption</value>
      <webElementGuid>bf124a99-01c5-4f9a-9739-74c8d4b20b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>evaluateText: '{{record.DirectQuoteNumberString}}', evaluateAttr: { title: '{{record.DirectQuoteNumberString}}' }</value>
      <webElementGuid>77479276-0edf-4190-a026-91dc2d422c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DQ002574-1</value>
      <webElementGuid>363469ed-3069-41e5-a89e-cd8eed996501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DQ002574-1</value>
      <webElementGuid>aa8d53d1-3e0f-4c79-bff8-17d9b56281ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectQuoteListContainer&quot;)/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-vertical Width100Percent&quot;]/div[@class=&quot;container-element layout-flow-vertical QuoteOrderFormBody&quot;]/div[@class=&quot;list SearchCardList&quot;]/div[@class=&quot;list-items-container&quot;]/div[@class=&quot;list-item&quot;]/div[@class=&quot;container-element layout-flow-vertical SearchCard&quot;]/div[@class=&quot;container-element layout-flow-horizontal SearchCardHeader&quot;]/a[@class=&quot;link SearchCardTitle&quot;]/span[@class=&quot;v-caption&quot;]</value>
      <webElementGuid>28609870-e5f5-4736-8929-a1fc41ca95b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_edb359</value>
      <webElementGuid>cca929d5-22f9-4ab2-9255-0e0f17280a48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirectQuoteListContainer']/div/div/div/div[2]/div[2]/div/div/div/div/a/span</value>
      <webElementGuid>7954f47f-78ff-45fa-938a-002ca97958b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/following::span[1]</value>
      <webElementGuid>1313e805-a6aa-4e1a-899a-5f5467328fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/following::span[2]</value>
      <webElementGuid>d3d9f18e-0443-4fbb-8d9f-10570d74f028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::span[2]</value>
      <webElementGuid>45f8b615-e620-4752-a78d-0ac1e2dc496f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[3]/preceding::span[3]</value>
      <webElementGuid>d4b63e5f-a542-4eb4-9b1f-982e92875839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DQ002574-1']/parent::*</value>
      <webElementGuid>5b07612d-16f5-4ca0-9db6-94e093abc553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/span</value>
      <webElementGuid>cb5c2192-3770-4ed8-a33d-38495e63ef53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'DQ002574-1' and (text() = 'DQ002574-1' or . = 'DQ002574-1')]</value>
      <webElementGuid>d12944b0-0710-41f7-9a73-4cadd25a6f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
