<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Configure</name>
   <tag></tag>
   <elementGuidId>106502ce-8a9a-413f-a9b6-fd2a878385ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='interactive']/span)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e67bd974-625e-45c7-9fde-6ead45ed787e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-caption</value>
      <webElementGuid>7f2cd7ae-b303-4ff0-a89f-c30ef3d3d745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>evaluateText: 'Configure', evaluateAttr: { title: '' }</value>
      <webElementGuid>6463f759-8213-48c1-a1aa-1e2fe492b08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configure</value>
      <webElementGuid>3da096db-8767-4c13-8d9a-842164a7cc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductCatalogMainBody&quot;)/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-vertical FormBody&quot;]/div[@class=&quot;container-element layout-flow-horizontal ContainerFixedAlign&quot;]/div[@class=&quot;rapid-options ProductCatalogItemDetails&quot;]/div[@class=&quot;rapid-options-actions collapsible&quot;]/a[@id=&quot;interactive&quot;]/span[@class=&quot;v-caption&quot;]</value>
      <webElementGuid>ee72b54f-4c59-4b27-b718-61f8791a201d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_ea9ac7</value>
      <webElementGuid>9bf4d6b4-def4-4653-ba39-d27c3f35ca9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='interactive']/span)[2]</value>
      <webElementGuid>2ba5ed32-cab4-4565-80fa-909ef8fa9f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[3]/following::span[1]</value>
      <webElementGuid>9be23e29-c48e-4747-8756-dd47dc25d6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Item'])[6]/following::span[2]</value>
      <webElementGuid>48ba4d74-e6b5-4531-bc5b-4298800487d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specifications'])[1]/preceding::span[1]</value>
      <webElementGuid>9d863ab0-fa27-40f6-bbe2-a4f31f21f722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/preceding::span[2]</value>
      <webElementGuid>f5e27b48-2231-414a-a61d-722e92c8be65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/span</value>
      <webElementGuid>ac269a7e-e9e7-4476-896a-02bd28b3fd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Configure' or . = 'Configure')]</value>
      <webElementGuid>15f0c3cd-9c02-41a5-9399-de5cf1ee4d99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
