<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_ARE</name>
   <tag></tag>
   <elementGuidId>6bdf790a-633c-4842-9e3f-46e7d84d76e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container-element.layout-flow-vertical.CustomerSelectionButtonContainer > a.button.button-element.with-text > span.v-caption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;navigation-target&quot;]/div/div[2]/div[1]/div[2]/div/div/div/div[2]/div[1]/div[1]/div/div[3]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>515de1f4-7ef9-483a-9197-b442dbc12bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-caption</value>
      <webElementGuid>c684e61b-2dea-4c3e-9d57-44f84a9438d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>evaluateText: 'Select', evaluateAttr: { title: '' }</value>
      <webElementGuid>9f717439-9bff-42c3-a88a-34e8f164eb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>d6e8f838-4584-46e7-bcbc-b322eff84dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-element layout-flow-horizontal RootContainer&quot;]/div[@class=&quot;navigation-target-parent&quot;]/div[@id=&quot;navigation-target&quot;]/div[@class=&quot;container-element layout-flow-vertical Overflow&quot;]/div[@class=&quot;container-element layout-flow-horizontal ContainerStretch&quot;]/div[@class=&quot;container-element layout-flow-vertical ContainerStretch&quot;]/div[@class=&quot;form-container evaluate-form-container ContainerStretch&quot;]/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-vertical ContainerFixedContentHeight&quot;]/div[@class=&quot;list&quot;]/div[@class=&quot;list-items-container&quot;]/div[@class=&quot;list-item&quot;]/div[@class=&quot;container-element layout-flow-horizontal CustomerSelectionLineContainer&quot;]/div[@class=&quot;container-element layout-flow-vertical CustomerSelectionButtonContainer&quot;]/a[@class=&quot;button button-element with-text&quot;]/span[@class=&quot;v-caption&quot;]</value>
      <webElementGuid>2918c4c6-e759-4c41-a795-59acf672b63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_ea9ac7</value>
      <webElementGuid>b5d6e765-7392-4d52-b4bd-81372489e401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation-target']/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div[3]/a/span</value>
      <webElementGuid>3e67d837-34a2-40a9-943f-5e5343ab48b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OHIO'])[1]/following::span[3]</value>
      <webElementGuid>ae2d600e-4e83-47a1-8034-c3ed10663fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=','])[2]/following::span[4]</value>
      <webElementGuid>d531e753-df04-4d2e-99a9-61a6a6764a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::span[1]</value>
      <webElementGuid>c3ea8e3a-e4e6-48fc-848f-1a9356084dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC1'])[1]/preceding::span[2]</value>
      <webElementGuid>61780ae0-795b-4746-bc0a-c376ac78d0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>afebaff4-d36f-4cc5-9c3b-ad7253d8c8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/a/span</value>
      <webElementGuid>7207b73a-8e85-4adb-97ef-691173216700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>6d22838c-e046-40ec-8a17-ea0f723d0563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
