<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Customer</name>
   <tag></tag>
   <elementGuidId>f2014936-7465-4e44-807f-cacd1c1bd83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DirectQuoteBody']/div/div/div/div/div/div/div/div/div[3]/a[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>20fde9bb-586e-4cce-a481-d5b9449aca69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-caption</value>
      <webElementGuid>5f31ab15-980c-40a4-9b0e-dd1494f10486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>evaluateText: 'Select Customer', evaluateAttr: { title: '' }</value>
      <webElementGuid>73ca1e8e-c4b0-4921-a1d2-b98f7d81f455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Customer</value>
      <webElementGuid>4cf1f35c-144a-43cd-a186-2e72e8673274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectQuoteBody&quot;)/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-horizontal ContainerStretch&quot;]/div[@class=&quot;container-element layout-flow-vertical QuoteBodyMainArea&quot;]/div[@class=&quot;form-container evaluate-form-container QuoteCustomerHeader&quot;]/div[@class=&quot;evaluate-display-entity&quot;]/div[@class=&quot;display-entity-container&quot;]/div[@class=&quot;container-element layout-flow-horizontal MobileQuoteCustomerHeader&quot;]/div[@class=&quot;container-element layout-flow-vertical QuoteCustomerHeaderChange&quot;]/a[@class=&quot;button button-element with-text with-icon Edit MobileSelectCustomerButtonTertiaryDark&quot;]/span[@class=&quot;v-caption&quot;]</value>
      <webElementGuid>55f1ac29-f260-4ff2-a8f3-7f73294fba55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Enterprise Quoting/iframe_Enjoy easier navigation and personal_ea9ac7</value>
      <webElementGuid>1daa74f6-5ca4-4659-83ce-90b3b72d6d1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirectQuoteBody']/div/div/div/div/div/div/div/div/div[3]/a[3]/span</value>
      <webElementGuid>5ea41cc2-e4c4-44b5-b360-2e649535bb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Customer'])[1]/following::span[1]</value>
      <webElementGuid>b98543ee-e5a3-4726-af75-055acea435f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Customer'])[1]/following::span[2]</value>
      <webElementGuid>114ac745-1d81-4993-9a21-9e14ab691542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last modified by Seth Romanowski on 2/17/2024 7:34 PM'])[1]/preceding::span[1]</value>
      <webElementGuid>70b10a4d-2cf2-4d22-a950-c9e19f10f21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lines: 0'])[1]/preceding::span[2]</value>
      <webElementGuid>236440a8-8c04-4da4-b4ec-ad45085edb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Customer']/parent::*</value>
      <webElementGuid>47369448-bb77-4655-ade7-c77b0813f5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>b5ebb661-1398-4c86-a210-9eca5856aa29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Customer' or . = 'Select Customer')]</value>
      <webElementGuid>2f0fe826-b1ca-4790-8cbf-dc45a81054e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
